theme: jekyll-theme-minimal
title: Gregor Bös
description: Welcome to my academic website. Content, academic as non-academic, still under construction.
email: gregor.boes@kcl.ac.uk

url:                 http://gboes.github.io/academic
baseurl:             /academic/

exclude:
 - README.md
