theme: jekyll-theme-minimal
title: Gregor Bös
description: Welcome to my academic website.
email: gregor.boes@kcl.ac.uk

url:                 http://gboes.github.io
baseurl:             ''
markdown: CommonMarkGhPages
exclude:
 - README.md

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-145857720-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
