theme: jekyll-theme-minimal
title: Gregor Bös
description: Welcome my academic website. Content, academic as non-academic, still under construction.
email: gregor.boes@kcl.ac.uk

exclude:
 - README.md
