theme: jekyll-theme-minimal
title: Gregor E. Bös
description: Welcome to my academic website.
email: gregor.boes@kcl.ac.uk

# url:                 https://gboes.github.io
url:                  https://gregorboes.com
baseurl:             ''
# markdown: CommonMarkGhPages
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]

exclude:
 - README.md

# Google Analytics:
google_analytics: UA-145857720-1
